# Generated by Django 3.0.3 on 2020-04-29 17:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Courseoutline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOutlineSection6',
            fields=[
                ('SectionID', models.AutoField(primary_key=True, serialize=False)),
                ('SectionName', models.CharField(default='Resources', max_length=55)),
                ('DateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('ResourcesTypes', models.CharField(choices=[('Text Book', 'Text Book'), ('Internet Resources', 'Internet Resources'), ('Research Paper', 'Reserach Paper')], max_length=20)),
                ('ResourcesDescription', models.TextField(max_length=3)),
                ('CourseOutlineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courseoutline.CourseOutline')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOutlineSection5',
            fields=[
                ('SectionID', models.AutoField(primary_key=True, serialize=False)),
                ('SectionName', models.CharField(default='Evaluation Plans', max_length=55)),
                ('DateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('EvaluationType', models.CharField(choices=[('Assignments', 'Assignments'), ('Quizzes', 'Quizzes'), ('Attendance', 'Attendance'), ('Midterm Exam', 'Midterm Exam'), ('Final Exam', 'Final Exam'), ('Projects', 'Projects')], max_length=20)),
                ('EvaluationPercentage', models.CharField(max_length=3)),
                ('CourseOutlineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courseoutline.CourseOutline')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOutlineSection4',
            fields=[
                ('SectionID', models.AutoField(primary_key=True, serialize=False)),
                ('SectionName', models.CharField(default='Course Topics', max_length=55)),
                ('DateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('CourseTopic', models.TextField(max_length=555)),
                ('CourseTopicDesc', models.TextField(max_length=555)),
                ('CourseOutlineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courseoutline.CourseOutline')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOutlineSection3',
            fields=[
                ('SectionID', models.AutoField(primary_key=True, serialize=False)),
                ('SectionName', models.CharField(default='Course Composition', max_length=55)),
                ('DateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('CourseDesc', models.TextField(max_length=555)),
                ('NumofLectureHrs', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2)),
                ('NumofAddLectureHrs', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2)),
                ('NumofLabHrs', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2)),
                ('NumofSSHrs', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2)),
                ('NumofAdvHrs', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2)),
                ('CourseOutlineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courseoutline.CourseOutline')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOutlineSection2',
            fields=[
                ('SectionID', models.AutoField(primary_key=True, serialize=False)),
                ('SectionName', models.CharField(default='Aims and Objectives', max_length=55)),
                ('DateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('CourseAims', models.TextField(max_length=555)),
                ('ObjofCourse', models.TextField(max_length=555)),
                ('CourseOutlineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courseoutline.CourseOutline')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOutlineSection1',
            fields=[
                ('SectionID', models.AutoField(primary_key=True, serialize=False)),
                ('SectionName', models.CharField(default='Course Identification and General Information', max_length=55)),
                ('DateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('NumberOfCredit', models.CharField(max_length=10)),
                ('CategoryofCourse', models.CharField(choices=[('Core Course', 'Core Course'), ('General Education Course', 'General Education Course'), ('Major Required Course', 'Major Required Course'), ('Major Elective Course', 'Major Elective Course')], max_length=55)),
                ('Prerequisite', models.CharField(max_length=100)),
                ('Corequisite', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('DateofCourseDevelopmentorRevision', models.DateField()),
                ('CourseOutlineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courseoutline.CourseOutline')),
            ],
        ),
    ]
