# Generated by Django 3.0.4 on 2020-05-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courseoutline', '0002_auto_20200504_1655'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='curriculum',
            table=None,
        ),
    ]
